### ISSUE TITLE
META6.json says license is Artistic, but code says GPL

### ISSUE THREAD

**Issue by ugexe** [croservices/openapi-styles#1]
Artistic:
https://github.com/croservices/openapi-styles/blob/4f2cc36f93097d4dd83a24680136a6e5b0aaf17b/META6.json#L8

GPL:
https://github.com/croservices/openapi-styles/blob/4f2cc36f93097d4dd83a24680136a6e5b0aaf17b/lib/OpenAPI/Styles.pm6#L2-L17
https://github.com/croservices/openapi-styles/blob/4f2cc36f93097d4dd83a24680136a6e5b0aaf17b/t/01-basic.t#L2-L17

**Comment by Altai-man** [comment]
Oh, I didn't remove those leftovers! Thanks, will do.
And README is wrong too. Fixed with latest commits.
